<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>c7280d4b-c822-4d1d-b623-b8089f134543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Apply&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbcc9f63-4dfc-4010-bcc6-1ba3bdd602c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d00f2ed4-d35c-4a06-a15f-fcf3573c53f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-t63o85 ant-btn-primary ant-btn-color-primary ant-btn-variant-solid shadow-none   w-full mt-3 rounded h-9 text-sm bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark text-textBaseWhiteLight dark:text-textBaseDarkDark border-none outline-0</value>
      <webElementGuid>2552a510-2925-4c78-8540-5a5a23a0955f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>e9aabd99-f60b-45ae-be52-efc1d3e6d31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@class=&quot;ant-popover-inner-content&quot;]/div[@class=&quot;min-w-[320px] sm:min-w-[400px]&quot;]/button[@class=&quot;ant-btn css-t63o85 ant-btn-primary ant-btn-color-primary ant-btn-variant-solid shadow-none   w-full mt-3 rounded h-9 text-sm bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark text-textBaseWhiteLight dark:text-textBaseDarkDark border-none outline-0&quot;]</value>
      <webElementGuid>b413e06e-4073-42f8-ab78-e178a5d401e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>47a965d0-694d-4b25-bf70-3d12dc2cd5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':rc:']/div/div/button</value>
      <webElementGuid>536e182c-b3b4-4137-a374-5f5d9a04c7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THB'])[1]/following::button[1]</value>
      <webElementGuid>173e8492-c59c-4b0d-932e-d68af8d508eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Currency'])[1]/following::button[1]</value>
      <webElementGuid>5c7e375e-322d-4905-8110-a3dd5ed9d462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel the World'])[1]/preceding::button[1]</value>
      <webElementGuid>f679fdac-f2a1-4019-b51c-4d62d7af84e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>b3fcbe46-65e6-4ddb-866a-d51c2567b016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>5aee565d-514c-4f82-9f74-9870e7e7cbb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
