<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_USD  ENG_text-iconDarkDark -ml-1 md-ml-0</name>
   <tag></tag>
   <elementGuidId>5a1a0dc3-87a7-408d-aaf9-b25c1f2e3826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='USD / ENG'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Main navigation&quot;i >> internal:role=img >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>cbef92d8-526f-4df3-88fd-fa6b1e123271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-iconDarkDark -ml-1 md:-ml-0</value>
      <webElementGuid>017873ae-1ba4-49c4-8a59-af7f9ec854a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>94f84453-bdf2-4de5-a7c8-b598760eb944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 18 18</value>
      <webElementGuid>425d5878-7cbb-4694-bc27-d9541e2eb790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>d5d84764-6a58-4f01-9bbe-c4b28151c439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8c7a11ad-d5b4-46b0-a43e-eebbd3b7718c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ee77fd80-eb52-499b-aeaa-9667586f3737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phx-nav-bar&quot;)/section[@class=&quot;container  mx-auto&quot;]/nav[@class=&quot;px-3 py-3 ms-0.5 md:ps-1 flex justify-start items-center gap-x-1 sm:gap-x-3 md:gap-x-6&quot;]/div[@class=&quot;flex items-center justify-between flex-1 gap-4 md:gap-6&quot;]/div[@class=&quot;w-fit flex items-center justify-end flex-1 gap-3 md:gap-6&quot;]/div[@class=&quot;min-w-7 sm:min-w-24 md:min-w-[140px] min-h-8 flex items-center&quot;]/div[@class=&quot;md:py-[3px] cursor-pointer flex gap-1 md:gap-2 items-center justify-center&quot;]/svg[@class=&quot;text-iconDarkDark -ml-1 md:-ml-0&quot;]</value>
      <webElementGuid>6a2635c4-1ad5-4d37-967c-7fc305cebf20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD / ENG'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>e5426a73-736e-47fa-8be5-247529d5fb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>a4e8945c-2e41-4741-a1e3-01df4486241d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel the World'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>e4d48ed4-d262-4333-8e80-b9e346c03b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='one adventure at a time'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>d2d68e6e-b291-492c-b123-de905e19a658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
