<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>75b96613-fbd6-4286-8efc-859ffc15bf9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfd9eff3-46a1-4fac-a7c5-11bd2444ef18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9f8cbd91-faa4-468d-959b-0877897a1fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e5d5f592-6120-4bcc-859e-8e50ab23a3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-fbugsh ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-block shadow-none   !text-base text-textBaseWhiteLight dark:text-textBaseDarkDark !leading-6 !h-14 bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark</value>
      <webElementGuid>43cec2c9-7a63-423d-8e84-b2ce2e5695d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>09771969-fc0d-4f31-8066-d42c2fd15f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tailwind-core&quot;)/body[@class=&quot;__className_a37cae layout_customScrollbar__E0DvH !w-full&quot;]/div[@class=&quot;css-1to9m9p ant-app&quot;]/main[@class=&quot;bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark min-h-full min-w-full&quot;]/main[@class=&quot;min-h-screen max-w-full overflow-hidden&quot;]/section[@class=&quot;relative w-full h-[720px] md:h-[840px] lg:h-[720px] bg-no-repeat bg-cover&quot;]/div[@class=&quot;container mx-auto relative z-30 h-full w-full&quot;]/div[2]/div[@class=&quot;relative&quot;]/div[@class=&quot;bg-surfaceBaseDarkLight dark:bg-surfaceBaseBg5Dark bg-opacity-40 dark:bg-opacity-40 py-4 sm:py-8 px-4 rounded-lg md:rounded-ss-none&quot;]/form[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col lg:flex-row justify-center items-center gap-2 z-10 w-full&quot;]/div[@class=&quot;flex-1 self-stretch lg:self-auto absolute -bottom-8 w-[298px] h-14 left-1/2 transform translate-x-[-50%]&quot;]/button[@class=&quot;ant-btn css-fbugsh ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-block shadow-none   !text-base text-textBaseWhiteLight dark:text-textBaseDarkDark !leading-6 !h-14 bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark&quot;]</value>
      <webElementGuid>31dd32a8-cbb8-4264-8e60-2b40d2f42668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>a6f57a6e-b930-466c-a646-0e17193ceb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='tailwind-core']/body/div[3]/main/main/section[2]/div[3]/div[2]/div[2]/div/form/div/div[4]/button</value>
      <webElementGuid>4ae0f272-7075-4c23-b3db-dca17c1a1168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guest'])[1]/following::button[1]</value>
      <webElementGuid>d7dce703-62dc-4e87-8146-31cc83e7390a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 27, 25'])[1]/following::button[2]</value>
      <webElementGuid>d0b6c752-24e5-4006-926c-660e8b9530d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveling For Business'])[1]/preceding::button[1]</value>
      <webElementGuid>e2e47596-d02c-4490-8a32-f5b39ffa11af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>ca584e30-ffbc-4ace-81e6-33bd44acf100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>e76b7639-a63c-4d8e-91d1-4c4304dbbd51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
