<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please Note_nav-user</name>
   <tag></tag>
   <elementGuidId>ad6ff8d3-2f95-4dc3-9110-6d4a2da4bfca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-user']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nav-user</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ca0838a-dee6-44bd-8985-7b9259a25482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-user</value>
      <webElementGuid>eb1c6839-c06f-4386-8edf-b524a0529154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-[0.5px] h-8 border-borderBaseWhiteLightLight dark:border-borderBaseWhiteLightDark  rounded-full px-1 cursor-pointer flex gap-1 sm:gap-2 items-center justify-center</value>
      <webElementGuid>123ca0e7-dac1-45d0-8506-c2ff6c89fb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:R2uhdsrbpmla:</value>
      <webElementGuid>b7d5440c-c639-43b3-8351-abdae34b2eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-user&quot;)</value>
      <webElementGuid>0c44eca0-28b4-45c9-bbae-00d5878f9c3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-user']</value>
      <webElementGuid>10065cb3-a148-49f9-ba38-35942a5730f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='phx-nav-bar']/section/nav/div/div/div[2]</value>
      <webElementGuid>b18bc13e-87d0-4bd6-b6cf-7453b21d3f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Note:'])[1]/following::div[7]</value>
      <webElementGuid>53c104f4-71d4-4882-a4d5-674473e19189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADVENTURE BETA RELEASE:'])[1]/following::div[7]</value>
      <webElementGuid>0cb7cdc6-9786-4218-a30a-39db20421ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel the World'])[1]/preceding::div[6]</value>
      <webElementGuid>72de88c9-0bbb-4ddc-90c2-73a4ee99de91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='one adventure at a time'])[1]/preceding::div[6]</value>
      <webElementGuid>904176f1-ae02-40d7-b3db-f2aa63b623de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>41991bf9-a348-424d-aa81-c9270ef88d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-user']</value>
      <webElementGuid>a1000314-900d-4c4e-ad61-4b724efaa49a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
